#!/usr/bin/env sh
# Cloudflare Pages build command — set as the project's "Build command".
#
# Templates web/config.js from the Pages env vars so the static web bundle
# can read window.DETOX_* at boot. Idempotent and side-effect-free
# beyond writing one file. Locally, the Flask agent serves /config.js
# dynamically, so this file should NOT be committed.

set -eu

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="${ROOT_DIR}/web/config.js"

: "${DETOX_SUPABASE_URL:=}"
: "${DETOX_SUPABASE_ANON_KEY:=}"
: "${DETOX_API_BASE:=}"

cat > "$OUT" <<EOF
/* Generated by infra/cloudflare/build.sh — do not edit by hand. */
window.DETOX_SUPABASE_URL = "${DETOX_SUPABASE_URL}";
window.DETOX_SUPABASE_ANON_KEY = "${DETOX_SUPABASE_ANON_KEY}";
window.DETOX_API_BASE = "${DETOX_API_BASE}";
EOF

echo "Wrote ${OUT}"
